#!/usr/bin/env python

'''
get tree of scripts with file name, size, and time of
modification
'''

import os
import glob

def prnDir(p1,p2,lev):
    s1="   "*lev
    s2=p1.replace("%s/" % p2,"")
    #print  "%s  %s" % (s1,s2)

def prnFile(f1,f2,lev):
     import time
     fileName, fileExtension = os.path.splitext(f1)
     if fileExtension == '.py':
          finfo=os.stat(f1)
          s1="   "*lev
          s2=f1.replace("%s/"%f2,"")
          s3=finfo.st_mtime
          s4=finfo.st_size
          #print "%s  %s " % (s1,s2)

def sortList(files):
     forder=[]
     for f in files:
         if os.path.isdir(f): d="d"
         else: d="x"
         forder.append((d+f, f))
     forder.sort()
     files1=[f for (d,f) in forder]
     return files1

pp=os.getcwd()
fileList1 = glob.glob("%s/*" % pp)

for f1 in sorted(fileList1):
    if not os.path.isdir(f1):
       prnFile(f1,pp,1)
       continue
    prnDir(f1,pp,1)
    fileList2 = glob.glob("%s/*" % f1)
    for f2 in sorted(fileList2):
        if not os.path.isdir(f2):
           prnFile(f2,f1,2)
           continue
        prnDir(f2,f1,2)
        fileList3 = glob.glob("%s/*" % f2)
        for f3 in sorted(fileList3):
             if not os.path.isdir(f3):
                  prnFile(f3,f2,3)
                  continue
             prnDir(f3,f2,3)
             fileList4 = glob.glob("%s/*" % f3)
             for f4 in sorted(fileList4):
                 if not os.path.isdir(f4):
                    prnFile(f4,f3,4)
                    continue
                 prnDir(f4,f3,4)
